apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinkub1
  namespace: dev
  labels:
    app: spinkub1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spinkub1
  template:
    metadata:
      labels:
        app: spinkub1
    spec:
      containers:
      - name: primary
        image: index.docker.io/cpalmer9/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000

---

apiVersion: v1
kind: Service
metadata:
  labels:
  name: spinkub1-svc
  namespace: dev
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: spinkub1
  type: LoadBalancer


