apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: dev
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinkub1
  namespace: dev
  labels:
    source: demo
    stack: frontend
    app: spinkub1
spec:
  replicas: 4
  selector:
    matchLabels:
      source: demo
      app: spinkub1
  template:
    metadata:
      labels:
        source: demo
        app: spinkub1
    spec:
      containers:
      - name: primary
        image: index.docker.io/cpalmer9/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinkub1
  namespace: dev
spec:
  selector:
    source: demo
    app: spinkub1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
